#设置服务名称
spring:
  application:
    name: micr-dataservice
#设置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ying_li_bao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 68963120g
#设置mybatis
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.xiaoguan.dataservice.service
  provider:
    timeout: 80000
    retries: 0
#密码加盐
ylb:
  config:
    pwdsalt: qwertyuiopasdfghjklzxcvbnm


